# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'converter.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(573, 697)
        MainWindow.setStyleSheet("background-color:#22222e")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, -10, 791, 270))
        self.widget.setStyleSheet("background-color:#ffff00")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(20, 40, 761, 131))
        font = QtGui.QFont()
        font.setFamily("NSimSun")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(190, 130, 191, 111))
        self.label_2.setText("")
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setPixmap(QtGui.QPixmap("sign.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.input_edinitsi = QtWidgets.QLineEdit(self.centralwidget)
        self.input_edinitsi.setGeometry(QtCore.QRect(100, 280, 380, 60))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.input_edinitsi.setFont(font)
        self.input_edinitsi.setStyleSheet("background-color:#22222e;border:2px solid#ffff00;border-radius:30;color:white;")
        self.input_edinitsi.setAlignment(QtCore.Qt.AlignCenter)
        self.input_edinitsi.setObjectName("input_edinitsi")
        self.input_chislo = QtWidgets.QLineEdit(self.centralwidget)
        self.input_chislo.setGeometry(QtCore.QRect(100, 360, 380, 60))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.input_chislo.setFont(font)
        self.input_chislo.setStyleSheet("background-color:#22222e;border:2px solid#ffff00;border-radius:30;color:white;")
        self.input_chislo.setAlignment(QtCore.Qt.AlignCenter)
        self.input_chislo.setObjectName("input_chislo")
        self.output_edinitsi = QtWidgets.QLineEdit(self.centralwidget)
        self.output_edinitsi.setGeometry(QtCore.QRect(100, 440, 380, 60))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.output_edinitsi.setFont(font)
        self.output_edinitsi.setStyleSheet("background-color:#22222e;border:2px solid#ffff00;border-radius:30;color:white;")
        self.output_edinitsi.setAlignment(QtCore.Qt.AlignCenter)
        self.output_edinitsi.setObjectName("output_edinitsi")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(100, 520, 380, 60))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setStyleSheet("background-color:#22222e;border:2px solid#ffff00;border-radius:30;color:white;")
        self.lineEdit_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(100, 600, 380, 60))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{background-color: #ffff00;border-radius: 30;color: black;} "
                                      "QPushButton: pressed {background-color: #fa4244;}")
        self.pushButton.setIconSize(QtCore.QSize(30, 30))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "КОНВЕРТОР СКОРОСТИ"))
        self.pushButton.setText(_translate("MainWindow", "Перевести"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
